network/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("post-comment/<str:action>", views.post_comment, name="post-comment"),
    path("user-profile/<int:user_id>", views.user_profile, name="user-profile"),
    path("edit-profile", views.edit_profile, name="edit-profile"),
    path("following", views.following, name="following"),
    path("follow-unfollow/<int:user_id>", views.follow_unfollow, name="follow-unfollow"),
    path("like/<str:action>/<int:action_id>", views.like, name="like"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/models.py
from django_countries.fields import CountryField
# django countries from https://pypi.org/project/django-countries/

from django.contrib.auth.models import AbstractUser
from django.db import models
from .util import resize_image


class User(AbstractUser):
    """ Model: User """
    pass


class UserProfile(models.Model):
    """
    Model: User Profile

    User Model extension with additional fields:
    * name - user's name
    * date_of_birth - user's birth date
    * about - additional info about the user
    * country - user's birth place
    * image - user's profile photo
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    name = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    about = models.TextField(blank=True, null=True)
    country = CountryField(blank=True, null=True)
    image = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        resize_image(self.image.path, 600, 600)


class Post(models.Model):
    """
    Model: Post - all post info

    fields:
    * user - who posted the post
    * content - post's inner text
    * date - post's publication date
    """

    # Model fields
    # auto: post-id
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="posted by", related_name="posts")
    content = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True, null=False, blank=True, verbose_name="posted on")

    # Model naming
    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"

    def __str__(self):
        return f"Post {self.id} made by {self.user} on {self.date.strftime('%d %b %Y %H:%M:%S')}"


class Comment(models.Model):
    """
    Model: Comment - all comment info

    fields:
    * user - who posted the comment
    * post - the post which is being commented
    * content - comment's inner text
    * date - comment's publication date
    """

    # Model fields
    # auto: comment-id
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="commented by")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True, null=False, blank=True, verbose_name="commented on")

    # Model naming
    class Meta:
        verbose_name = "comment"
        verbose_name_plural = "comments"
        ordering = ["date"]

    def __str__(self):
        return f"Comment {self.id} made by {self.user} on post {self.post_id} on {self.date.strftime('%d %b %Y %H:%M:%S')}"


class Like(models.Model):
    """
    Model: Like - all like info

    fields:
    * user - who liked a post/comment
    * post - the post which is being liked
    * comment - the comment which is being liked
    * emoji_type - the emoji used as a like, available emojis:
        1. like
        2. dislike
        3. smile
        4. heart
        5. thanks
    """

    # Emojis - choices
    LIKE_TYPE_CHOICES = [
        (1, "like"),
        (2, "dislike"),
        (3, "smile"),
        (4, "heart"),
        (5, "thanks")
    ]

    # Model fields
    # auto: like id
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="liked by")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes", null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="likes", null=True, blank=True)
    emoji_type = models.IntegerField(choices=LIKE_TYPE_CHOICES, default=1)

    # Model naming
    class Meta:
        verbose_name = "like"
        verbose_name_plural = "likes"
        unique_together = [["user", "post"], ["user", "comment"]]
        ordering = ["emoji_type"]

    def __str__(self):
        element = self.post if (self.post is not None) else self.comment
        return f"Like {self.id} by {self.user} on object {element}"


class Following(models.Model):
    """
    Model: Following - all who follows who info

    fields:
    * user - user who is following
    * user_followed - user who is being followed
    """

    # Model fields
    # auto: following id
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    user_followed = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers" )

    class Meta:
        verbose_name = "following"
        verbose_name_plural = "followings"
        unique_together = ['user', 'user_followed']

    def __str__(self):
        return f"{self.user} is following {self.user_followed}"

    def get_user_followed_posts(self):
        """ Get all the posts from users that the current user follows """

        return self.user_followed.posts.order_by("-date").all()

network/views.py
import json
from itertools import chain

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import JsonResponse

from django.conf import settings

from .models import User, Post, Comment, Like, Following, UserProfile
from .forms import CreatePostForm, CreateCommentForm, CreateUserProfileForm

#TODO: custom 404 page

def index(request):
    """ View: Show all posts """

    # Get all posts
    all_posts = Post.objects.order_by("-date").all()

    # Create page controll
    paginator = Paginator(all_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "network/index.html", {
        "post_form": CreatePostForm(),
        "comment_form": CreateCommentForm(auto_id=False),
        "page_obj": page_obj,
        "add_post_available": True
    })

@login_required(login_url="network:login")
def post_comment(request, action):
    """ View: Controls saving a new post/comment (only POST) """

    # Get not allowed
    if request.method == "GET":
        return HttpResponse(status=405)

    if request.method == "POST":
        if action == "post":
            form = CreatePostForm(request.POST)

            if form.is_valid():
                # Get all data from the form
                content = form.cleaned_data["content"]

                # Save the record
                post = Post(
                    user = User.objects.get(pk=request.user.id),
                    content = content
                )
                post.save()
        elif action == "comment":
            form = CreateCommentForm(request.POST)

            if form.is_valid():
                # Get all data from the form
                content = form.cleaned_data["content"]

                # Get commented post
                try:
                    post = Post.objects.get(pk=request.POST.get('postId'))
                except Post.DoesNotExist:
                    return HttpResponse(status=404)

                # Save the record
                comment = Comment(
                    user = User.objects.get(pk=request.user.id),
                    content = content,
                    post = post
                )
                comment.save()

        # Go back to the place from which the request came
        return HttpResponseRedirect(request.headers['Referer'])

    if request.method == "PUT":
        body = json.loads(request.body)
        # Query for requested post - make sure
        # that current user is the author
        try:
            if action == "post":
                object_to_edit = Post.objects.get(pk=body.get('id'), user=request.user)
            else:
                object_to_edit = Comment.objects.get(pk=body.get('id'), user=request.user)
        except (Post.DoesNotExist, Comment.DoesNotExist):
            return JsonResponse({
                "error": "Post or Comment does not exist"
            }, status=404)

        # Update post's content
        object_to_edit.content = body.get('content')
        object_to_edit.save()

        # Return positive response
        return HttpResponse(status=201)

    if request.method == "DELETE":
        body = json.loads(request.body)
        # Query for requested post - make sure
        # that current user is the author
        try:
            if action == "post":
                object_to_delete = Post.objects.get(pk=body.get('id'), user=request.user)
            else:
                object_to_delete = Comment.objects.get(pk=body.get('id'), user=request.user)
        except (Post.DoesNotExist, Comment.DoesNotExist):
            return JsonResponse({
                "error": "Post or Comment does not exist"
            }, status=404)

        # Delete the post and refresh the page
        object_to_delete.delete()
        return HttpResponse(status=204)

@login_required(login_url="network:login")
def user_profile(request, user_id):
    """ View: Shows requested user profile and the user's posts """

    user_data = User.objects.get(pk=user_id)
    posts = user_data.posts.order_by("-date").all()

    # Get following and followed user objects
    following_id_list = Following.objects.filter(user=user_id).values_list('user_followed', flat=True)
    followers_id_list = Following.objects.filter(user_followed=user_id).values_list('user_id', flat=True)

    following_user_list = User.objects.filter(id__in=following_id_list)
    followers_user_list = User.objects.filter(id__in=followers_id_list)

    # Create page controll
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "network/user_profile.html", {
        "user_data": user_data,
        "following": following_user_list,
        "followers": followers_user_list,
        "page_obj": page_obj,
        "comment_form": CreateCommentForm(auto_id=False)
    })

@login_required(login_url="network:login")
def edit_profile(request):
    """ View: Controls editing of user profile's data """

    if request.method == "POST":
        # Cancel edit -> go back to the profile
        if request.POST.get("cancel") == "clicked":
            return HttpResponseRedirect(reverse(
                    "network:user-profile",
                    args=[request.user.id]
                ))

        # Submit edit -> update profile
        form = CreateUserProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            # Get current user's profile
            new_profile = UserProfile.objects.get(user=request.user.id)

            # Update all profile's data with form's data
            new_profile.name = form.cleaned_data.get("name")
            new_profile.date_of_birth = form.cleaned_data.get("date_of_birth")
            new_profile.about = form.cleaned_data.get("about")
            new_profile.country = form.cleaned_data.get("country")
            # Update image only if any file was uploaded
            if len(request.FILES) == 1:
                new_profile.image = request.FILES['image']

            # Save changes
            new_profile.save()

            # Go back to user's profile page
            return HttpResponseRedirect(reverse(
                    "network:user-profile",
                    args=[request.user.id]
                ))
        else:
            # If form invalid - load edit-profile with error info
            return render(request, "network/edit_profile.html", {
                "form": form,
                "max_file_size": settings.MAX_UPLOAD_SIZE
            })

    return render(request, "network/edit_profile.html", {
        "form": CreateUserProfileForm(instance=request.user.profile),
        "max_file_size": settings.MAX_UPLOAD_SIZE
    })

@login_required(login_url="network:login")
def like(request, action, action_id):
    """ View: Controls all actions regarding liking """

    if request.method == "GET":
        # Check if like exists and send back info
        try:
            if action == "post":
                post = Post.objects.get(pk=action_id)
                like_obj = Like.objects.get(user=request.user, post=post)
            elif action == "comment":
                comment = Comment.objects.get(pk=action_id)
                like_obj = Like.objects.get(user=request.user, comment=comment)
            else:
                return JsonResponse({
                    "error": "Unknown action - you can only like post or comment"
                }, status=400)
        except Like.DoesNotExist:
            return JsonResponse({
                "like": "False"
            }, status=200)
        except (Post.DoesNotExist, Comment.DoesNotExist):
            return JsonResponse({
                "error": "Post or Comment does not exist"
            }, status=404)
        # if like exists send emojiType text
        else:
            return JsonResponse({
                "like": "True",
                "emojiType": [emoji_tuple[1] for emoji_tuple in Like.LIKE_TYPE_CHOICES if emoji_tuple[0] == like_obj.emoji_type][0]
            }, status=200)
        # Something went wrong
        return JsonResponse({
                "error": f"Unknown error during GET {action} like "
        }, status=400)

    elif request.method == "POST":
        body = json.loads(request.body)
        emoji_type = [emoji_tuple[0] for emoji_tuple in Like.LIKE_TYPE_CHOICES if emoji_tuple[1] == body['emojiType']][0]

        try:
            if action == "post":
                post = Post.objects.get(pk=action_id)
                like_obj = Like(user=request.user, post=post, emoji_type=emoji_type)
            elif action == "comment":
                comment = Comment.objects.get(pk=action_id)
                like_obj = Like(user=request.user, comment=comment, emoji_type=emoji_type)
            else:
                return JsonResponse({
                    "error": "Unknown action - you can only like post or comment"
                }, status=400)
        except (Post.DoesNotExist, Comment.DoesNotExist):
            return JsonResponse({
                "error": "Post or Comment does not exist"
            }, status=404)

        like_obj.save()
        return HttpResponse(status=201)

    elif request.method == "PUT":
        body = json.loads(request.body)
        emoji_number = [emoji_tuple[0] for emoji_tuple in Like.LIKE_TYPE_CHOICES if emoji_tuple[1] == body['emojiType']][0]
        try:
            if action == "post":
                post = Post.objects.get(pk=action_id)
                old_like = Like.objects.get(user=request.user, post=post)
            elif action == "comment":
                comment = Comment.objects.get(pk=action_id)

network/templates/network/edit_profile.html
{% extends "network/layout.html" %}
{% load static %}
{% load i18n %}

{% block extra_css %}
    {{ form.media.css }}
    <link href="{% static 'network/forms.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="edit-profile">
    <!-- based on https://stackoverflow.com/a/14647770 -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="alert alert-danger hidden" id="file-size-error">
        <strong>{% blocktranslate %}Image file exceeds {{ max_file_size }} MB size limit{% endblocktranslate %}</strong>
    </div>
    <div class="alert alert-danger hidden" id="file-type-error">
        <strong>{% trans "File must be type image" %}</strong>
    </div>
    
    <div class="edit-profile-form create-listing-form info-card">
        <form action="{% url 'network:edit-profile'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label }}
                {{ form.name }}
            </div>
            <div class="form-group">
                <!-- date-picker based on: https://github.com/monim67/django-flatpickr -->
                {{ form.date_of_birth.label }}
                {{ form.date_of_birth }}
            </div>
            <div class="form-group">
                {{ form.about.label }}
                {{ form.about }}
            </div>
            <div class="form-group">
                {{ form.country.label }}
                <div class="country-field">
                    {{ form.country }}
                </div>
            </div>
            <div class="form-group">
                {{ form.image.label }}
                <div class="custom-file">
                    <input type="file" name="image" class="custom-file-input" accept="image/*" id="id_image">
                    {% if LANGUAGE_CODE == "pl" %}
                        <label class="custom-file-label" data-browse="Wybierz" for="id_image" data-default="Wybierz plik">Wybierz plik</label>
                    {% else %}
                        <label class="custom-file-label" data-browse="Browse" for="id_image" data-default="Choose file">Choose file</label>
                    {% endif %}
                </div>
            </div>
            <button class="btn btn-secondary" name="cancel" value="clicked">{% trans "Cancel" %}</button></a>  
            <input class="btn btn-success" type="submit" value={% trans "Submit" %}>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    {{ form.media.js }}
    <script src="{% static 'network/edit_profile_functions.js' %}"></script>
{% endblock %}
        

network/templates/network/layout.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
{% get_current_language_bidi as LANGUAGE_BIDI %} 

<html lang="en" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Emojis CSS -->
        <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
        <link href="{% static 'network/main_styles.css' %}" rel="stylesheet">
        <link href="{% static 'network/post_comment_styles.css' %}" rel="stylesheet">
        {% block extra_css %}
        {% endblock %}
    </head>
    <body>
        <nav class="nav-grid bg-light">
            <a class="network-link" href="{% url 'network:index'%}">Network</a>
            <nav class="navbar navbar-expand-md navbar-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                    </svg>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:user-profile' user_id=user.id%}"><strong>{{ user.username }}</strong></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'network:index'%}">{% trans "All Posts" %}</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:following'%}">{% trans "Following" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:logout' %}">{% trans "Log Out" %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:login' %}">{% trans "Log In" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:register' %}">{% trans "Register" %}</a>
                        </li>
                    {% endif %}
                  </ul>
                </div>
              </nav>
        </nav>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <script src="{% url 'javascript-catalog' %}"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

network/templates/network/posts.html
{% load custom_tags %}
{% load i18n %}

<div class="post-comment-element">
    <div class="post" id='post_{{ post.id }}'>
        <div class="post-user">
            <img class="round-picture post-profile-picture" src="{{ post.user.profile.image.url }}" title={{ post.user }} alt="profile picture">
            <a href="{% url 'network:user-profile' user_id=post.user.id %}">{{ post.user }}</a>
        </div>
        {% if user.id == post.user.id %}
            <div class="delete-edit-panel">
                <div class="dropdown">
                    <a class="btn icon-button" href="#" role="button" id="dropdownMenuLink_{{ post.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="rgb(101, 103, 107)" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                        </svg>
                    </a>
                
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink_{{ post.id }}">
                        <button class="dropdown-item dropdown-edit" data-toggle="modal" data-target="#modal_edit_post_{{ post.id }}">{% trans "Edit" %}</button>
                        <button class="dropdown-item dropdown-delete" data-toggle="modal" data-target="#modal_delete_post_{{ post.id }}">{% trans "Delete" %}</button>
                    </div>
                </div>
            </div>

            <!-- Modals -->
            <div class="modal fade delete-modal" id="modal_delete_post_{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="modal_delete_post_{{ post.id }}_label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="modal_delete_post_{{ post.id }}_label">{% trans "Are you sure?" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            {% trans "Are you sure you want to delete this post? This procedure is irreversible!" %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary modal-close" data-dismiss="modal">{% trans "Close" %}</button>
                            <button type="button" class="btn btn-danger modal-delete">{% trans "Delete" %}</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade edit-modal" id="modal_edit_post_{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="modal_edit_post_{{ post.id }}_label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="modal_edit_post_{{ post.id }}_label">{% trans "What did you really want to say?" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary modal-close" data-dismiss="modal">{% trans "Close" %}</button>
                            <button type="button" class="btn btn-primary modal-save">{% trans "Save" %}</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="post-date">
            {% trans "Posted: " %} {{post.date|timesince}} {% trans "ago" %}
        </div>
        <div class="content post-content short">
            {{ post.content}}
        </div>
        <div class="show-more hidden">{% trans "Show more" %}</div>
        <div class="like-data">
            <ul class="emoji-list">
                {% for emoji in post.likes.all %}     
                    {% ifchanged emoji.get_emoji_type_display%}   
                        {% if emoji.get_emoji_type_display == "like" %}
                            <i class="em em---1" aria-role="presentation" aria-label="THUMBS UP SIGN" data-count={% get_emoji_count post 'like' %} data-name="like"></i>
                        {% elif emoji.get_emoji_type_display == "dislike" %}
                            <i class="em em--1" aria-role="presentation" aria-label="THUMBS DOWN SIGN" data-count={% get_emoji_count post 'dislike' %} data-name="dislike"></i>
                        {% elif emoji.get_emoji_type_display == "smile" %}
                            <i class="em em-smile" aria-role="presentation" aria-label="SMILING FACE WITH OPEN MOUTH AND SMILING EYES" data-count={% get_emoji_count post 'smile' %} data-name="smile"></i>
                        {% elif emoji.get_emoji_type_display == "heart" %}
                            <i class="em em-heart" aria-role="presentation" aria-label="HEAVY BLACK HEART" data-count={% get_emoji_count post 'heart' %} data-name="heart"></i>
                        {% elif emoji.get_emoji_type_display == "thanks" %}
                            <i class="em em-bouquet" aria-role="presentation" aria-label="BOUQUET" data-count={% get_emoji_count post 'thanks' %} data-name="thanks"></i>
                        {% endif  %}  
                    {% endifchanged %}                
                {% endfor %}
            </ul>
            <span class="like-counter"></span>
        </div>
        <div class="comment-data">
            <span class="comment-count">{% trans "Comments:" %} {{post.comments.all.count}}</span>
        </div>
        {% if user.is_authenticated %}
        <div class="like-comment-control">
            <div class="like-panel">
                <button class="like-button" name="like">{% trans "Like" %}</button>
                <div class="emoji-choice hidden">
                    <ul>
                        <i class="em em---1" aria-role="presentation" aria-label="THUMBS UP SIGN" data-name="like"></i>
                        <i class="em em--1" aria-role="presentation" aria-label="THUMBS DOWN SIGN" data-name="dislike"></i>
                        <i class="em em-smile" aria-role="presentation" aria-label="SMILING FACE WITH OPEN MOUTH AND SMILING EYES" data-name="smile"></i>
                        <i class="em em-heart" aria-role="presentation" aria-label="HEAVY BLACK HEART" data-name="heart"></i>
                        <i class="em em-bouquet" aria-role="presentation" aria-label="BOUQUET" data-name="thanks"></i>
                    </ul>
                </div>
            </div>
            <button class="comment-button" data-toggle="collapse" data-target="#post_{{ post.id }} ~ .comment-section" aria-expanded="false" aria-controls="comment-section">{% trans "Comments" %}</button>
        </div>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
    <div class="comment-section collapse multi-collapse">
        {% for comment in post.comments.all %}
            {% include "network/comments.html"%}
            <hr class="comment-separation">
        {% endfor %}
        <div class="comment-form-wrapper">
            <a href="{% url 'network:user-profile' user_id=user.id %}">
                <img class="round-picture comment-profile-picture" src="{{ user.profile.image.url }}" title={{ user }} alt="profile picture">
            </a>
            <form action="{% url 'network:post-comment' action='comment' %}" method="post">
                {% csrf_token %}
                <div class="comment-form-content">
                    {{ comment_form.content}}
                    <button type="submit" class="icon-button">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-chat-fill" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
                        </svg>
                    </button>
                    <input type="hidden" name="postId" value={{ post.id }}>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
</div>